### ISSUE TITLE
BAM File Download Permission Error

### ISSUE THREAD

**Issue by mossnicholas** [shendurelab/mouse-atac#6]
Hi,

When I try to download download individual BAM files from the sci-ATAC-seq Atlas site, I get permission error. Same error  when using the suggested command line tools (wget or curl). Any solution to this?

**Comment by cusanovich** [comment]
I've updated the links. It should work now. Please let me know if it's still giving you problems.

**Comment by GrossTor** [comment]
Unfortunately, permission errors still appear, see https://github.com/shendurelab/mouse-atac/issues/4. Could you have a look @cusanovich ?
